use_frameworks!

target 'SharedNetworkActivityIndicator_Example' do
  pod 'SharedNetworkActivityIndicator', :path => '../'

  target 'SharedNetworkActivityIndicator_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  #pod 'FBSnapshotTestCase'
  #pod 'Expecta+Snapshots'
  end
end
