# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - rvm get head
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
  - open -a "simulator" --args -CurrentDeviceUDID `instruments -s devices | sed -n '/^iPhone 6s (10\.0) \[\(.*\)\].*$/s//\1/p'`
script:
  - set -o pipefail && travis_retry xcodebuild test -workspace Example/SharedNetworkActivityIndicator.xcworkspace -scheme SharedNetworkActivityIndicator-Example -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
